/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createServerRootRoute } from '@tanstack/react-start/server'

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedLogoutRouteImport } from './routes/_authed/logout'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as AuthedProcurementRouteRouteImport } from './routes/_authed/procurement/route'
import { Route as AuthedProcurementMaterialRequisitionRouteImport } from './routes/_authed/procurement/material-requisition'
import { ServerRoute as ApiTrpcSplatServerRouteImport } from './routes/api.trpc.$'

const rootServerRouteImport = createServerRootRoute()

const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedLogoutRoute = AuthedLogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => authRouteRoute,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => authRouteRoute,
} as any)
const AuthedProcurementRouteRoute = AuthedProcurementRouteRouteImport.update({
  id: '/procurement',
  path: '/procurement',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedProcurementMaterialRequisitionRoute =
  AuthedProcurementMaterialRequisitionRouteImport.update({
    id: '/material-requisition',
    path: '/material-requisition',
    getParentRoute: () => AuthedProcurementRouteRoute,
  } as any)
const ApiTrpcSplatServerRoute = ApiTrpcSplatServerRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootServerRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof authRouteRouteWithChildren
  '/procurement': typeof AuthedProcurementRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/login': typeof authLoginRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/logout': typeof AuthedLogoutRoute
  '/procurement/material-requisition': typeof AuthedProcurementMaterialRequisitionRoute
}
export interface FileRoutesByTo {
  '/': typeof authRouteRouteWithChildren
  '/procurement': typeof AuthedProcurementRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/login': typeof authLoginRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/logout': typeof AuthedLogoutRoute
  '/procurement/material-requisition': typeof AuthedProcurementMaterialRequisitionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(auth)': typeof authRouteRouteWithChildren
  '/_authed': typeof AuthedRouteWithChildren
  '/_authed/procurement': typeof AuthedProcurementRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/login': typeof authLoginRoute
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_authed/logout': typeof AuthedLogoutRoute
  '/_authed/procurement/material-requisition': typeof AuthedProcurementMaterialRequisitionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/procurement'
    | '/forgot-password'
    | '/login'
    | '/dashboard'
    | '/logout'
    | '/procurement/material-requisition'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/procurement'
    | '/forgot-password'
    | '/login'
    | '/dashboard'
    | '/logout'
    | '/procurement/material-requisition'
  id:
    | '__root__'
    | '/'
    | '/(auth)'
    | '/_authed'
    | '/_authed/procurement'
    | '/(auth)/forgot-password'
    | '/(auth)/login'
    | '/_authed/dashboard'
    | '/_authed/logout'
    | '/_authed/procurement/material-requisition'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authRouteRoute: typeof authRouteRouteWithChildren
  AuthedRoute: typeof AuthedRouteWithChildren
}
export interface FileServerRoutesByFullPath {
  '/api/trpc/$': typeof ApiTrpcSplatServerRoute
}
export interface FileServerRoutesByTo {
  '/api/trpc/$': typeof ApiTrpcSplatServerRoute
}
export interface FileServerRoutesById {
  __root__: typeof rootServerRouteImport
  '/api/trpc/$': typeof ApiTrpcSplatServerRoute
}
export interface FileServerRouteTypes {
  fileServerRoutesByFullPath: FileServerRoutesByFullPath
  fullPaths: '/api/trpc/$'
  fileServerRoutesByTo: FileServerRoutesByTo
  to: '/api/trpc/$'
  id: '__root__' | '/api/trpc/$'
  fileServerRoutesById: FileServerRoutesById
}
export interface RootServerRouteChildren {
  ApiTrpcSplatServerRoute: typeof ApiTrpcSplatServerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/logout': {
      id: '/_authed/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof AuthedLogoutRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/_authed/procurement': {
      id: '/_authed/procurement'
      path: '/procurement'
      fullPath: '/procurement'
      preLoaderRoute: typeof AuthedProcurementRouteRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/procurement/material-requisition': {
      id: '/_authed/procurement/material-requisition'
      path: '/material-requisition'
      fullPath: '/procurement/material-requisition'
      preLoaderRoute: typeof AuthedProcurementMaterialRequisitionRouteImport
      parentRoute: typeof AuthedProcurementRouteRoute
    }
  }
}
declare module '@tanstack/react-start/server' {
  interface ServerFileRoutesByPath {
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
  }
}

interface authRouteRouteChildren {
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authLoginRoute: typeof authLoginRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authForgotPasswordRoute: authForgotPasswordRoute,
  authLoginRoute: authLoginRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface AuthedProcurementRouteRouteChildren {
  AuthedProcurementMaterialRequisitionRoute: typeof AuthedProcurementMaterialRequisitionRoute
}

const AuthedProcurementRouteRouteChildren: AuthedProcurementRouteRouteChildren =
  {
    AuthedProcurementMaterialRequisitionRoute:
      AuthedProcurementMaterialRequisitionRoute,
  }

const AuthedProcurementRouteRouteWithChildren =
  AuthedProcurementRouteRoute._addFileChildren(
    AuthedProcurementRouteRouteChildren,
  )

interface AuthedRouteChildren {
  AuthedProcurementRouteRoute: typeof AuthedProcurementRouteRouteWithChildren
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedLogoutRoute: typeof AuthedLogoutRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedProcurementRouteRoute: AuthedProcurementRouteRouteWithChildren,
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedLogoutRoute: AuthedLogoutRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authRouteRoute: authRouteRouteWithChildren,
  AuthedRoute: AuthedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
const rootServerRouteChildren: RootServerRouteChildren = {
  ApiTrpcSplatServerRoute: ApiTrpcSplatServerRoute,
}
export const serverRouteTree = rootServerRouteImport
  ._addFileChildren(rootServerRouteChildren)
  ._addFileTypes<FileServerRouteTypes>()
